### ISSUE TITLE
Incompatibility with Refined Storage 2.0.0-beta.2 — Crash on Tooltip Rendering (UpgradeDestinationClientTooltipComponent)

### ISSUE THREAD

**Issue by andreasgoethals** [starforcraft/Cable-Tiers#72]
When hovering over an upgrade item (e.g. Fortune II Upgrade) in JEI with both Refined Storage and Cable Tiers installed, Minecraft crashes due to a Mixin error in MixinUpgradeDestinationClientTooltipComponent.

It appears that the Cable Tiers mod is attempting to overwrite the renderImage method in UpgradeDestinationClientTooltipComponent, but that method is not present (or the class has changed) in Refined Storage 2.0.0-beta.2.

**Comment by starforcraft** [comment]
Are you sure you're using beta.2? Also send me the whole crash report

**Comment by CplPibald-2** [comment]
[crash-2025-04-30_21.42.43-client.txt](https://github.com/user-attachments/files/19996502/crash-2025-04-30_21.42.43-client.txt)

**Comment by starforcraft** [comment]
Unfortunately I can't reproduce the crash, but I think this version should fix the issue, so could you please try this version?:
https://www.curseforge.com/minecraft/mc-mods/cable-tiers/files/6483054

**Comment by starforcraft** [comment]
Is it fixed now?

**Comment by CplPibald-2** [comment]
Can you put up a fabric version to test?

**Comment by starforcraft** [comment]
Woops seems like I accidentally uploaded the wrong version. Here is the right link: https://www.curseforge.com/minecraft/mc-mods/cable-tiers/files/6484357

**Comment by CplPibald-2** [comment]
Still crashing using 0.2.4 when hovering over RS blocks in JEI

[crash-2025-05-01_21.44.34-client.txt](https://github.com/user-attachments/files/20008439/crash-2025-05-01_21.44.34-client.txt)

**Comment by starforcraft** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/cable-tiers/files/6486651

**Comment by CplPibald-2** [comment]
Seems to work.  No crashes when hovering over items, and I can spawn them all in.  Tested both on SP and server.

Thanks!


(BTW, next thing I noticed while testing...  The upgraded disk interfaces have no texture.  When you place them, they become an x-ray hole in the world.   LMK if you want a new issue filed for that)

**Comment by starforcraft** [comment]
Fixed: https://legacy.curseforge.com/minecraft/mc-mods/cable-tiers/files/6486953
